[phases.setup]
nixPkgs = ['php82', 'nodejs_20', 'mariadb', 'curl', 'git']


[phases.install]
cmds = [
  'curl -sS https://getcomposer.org/installer | php',
  'php composer.phar install --no-dev --optimize-autoloader'
]

[phases.build]
cmds = [
  'php artisan config:cache',
  'php artisan migrate --force || true'
]

[phases.start]
cmd = 'php artisan serve --host 0.0.0.0 --port $PORT'
